# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 418a94e3b58abc0fad358cb36e1917865f5f8db691d657103627e91403898418036375ffcae96948855c7b37c79afd948927ddc3112ba24e6d8948b632ebc355

test:
  secret_key_base: c11545456a9cbcaf72f1f724f34eaae8d2de9edd2fdb1bd3c6683978027febb11861191217b0ba7a11de9423f87b3834baf217e56023289cd2ed8d6561dea2ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
